### ISSUE TITLE
Make sure creating a new GM, M, C, DEC, instances through the Admin, they MUST be connected to a shop

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#128]

**Comment by ziadnabil** [comment]
Done, Every GM, M, C, DEC must connected to a shop when created

**Comment by shahwan42** [comment]
@ziadnabil connect it to the corresponding Pull Request and close it please

**Comment by ziadnabil** [comment]
> @ziadnabil connect it to the corresponding Pull Request and close it please

@

**Comment by ziadnabil** [comment]
@shahwan42  we have done it through many pull requests I think, I just checked this time I didnt code
