### ISSUE TITLE
Design the HomePage of the web

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#137]
Show shop list for existing shops in the system in form of a Grid of cards
after clicking the shop card, it should redirect to the shop's products (storefront) which lists all the products for the shop

Design using Bootstrap5 through bootstrap studio or code it yourself... whatever's convenient for you

![image](https://user-images.githubusercontent.com/6496157/112781113-7f245800-904a-11eb-8f5b-3f57655f256e.png)

**Comment by MuhammadSamy1** [comment]
here is my design to home and store front pages. I kept it simple and used random images that we will change later.
[homepage.zip](https://github.com/egypt-shops/xshop-web/files/6228890/homepage.zip)
[storefront.zip](https://github.com/egypt-shops/xshop-web/files/6228893/storefront.zip)

**Comment by shahwan42** [comment]
![image](https://user-images.githubusercontent.com/6496157/112997473-70829180-916d-11eb-9c53-caf0e85be37d.png)
عظيم جداً
بس مكان السيرش مش واضح كفاية وأعتقد مش مناسب
الأفضل لو هتخليه فوق، يبقى على اليمين والباكجراوند تكون مختلفة شوية توضح امكان البحث
خلي فيها placeholder
search for a shop...
مثلاً

**Comment by MuhammadSamy1** [comment]
عملت تعديلين للسيرش اختار ما بينهم 
[HomePage #3.zip](https://github.com/egypt-shops/xshop-web/files/6242016/HomePage.3.zip)
[HomePage#2.zip](https://github.com/egypt-shops/xshop-web/files/6242017/HomePage.2.zip)

**Comment by shahwan42** [comment]
2 is better, thanks <3

**Comment by shahwan42** [comment]
انقل الفوتر للون اللي تحت عشان المعلومات دي أفضل تبقى جوا الفوتر الملون ده
ثم اعمل ده بقى في الديزاين التاني برده، عشان الفوتر يبقى حاجة ثابتة في معظم الصفحات

![image](https://user-images.githubusercontent.com/6496157/113404214-16b9db80-93a8-11eb-8fbe-dbfd6ab2e8ba.png)

وعاش ياسطى :heart:

**Comment by MuhammadSamy1** [comment]
here’s the last edit for HomePage design: 1- edited Footer BG color.
2- Head BG color.
3- added the Logo.
[HomePage#2(Edited).zip](https://github.com/egypt-shops/xshop-web/files/6274927/HomePage.2.Edited.zip)

**Comment by mmostafa74** [comment]
@HMMK99  please update home page with latest update
