### ISSUE TITLE
the storefront design

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#140]
Here we discuss the storefront design...

التعليقات ع الديزاين معمولة في الصورة
![image](https://user-images.githubusercontent.com/6496157/112998255-2817a380-916e-11eb-9921-cf9e85d24569.png)

**Comment by MuhammadSamy1** [comment]
تم التعديل
[StoreFront #2.zip](https://github.com/egypt-shops/xshop-web/files/6241472/StoreFront.2.zip)

**Comment by MuhammadSamy1** [comment]
تم التعديل وإضافة السورس
[StoreFront #2.zip](https://github.com/egypt-shops/xshop-web/files/6241523/StoreFront.2.zip)

**Comment by shahwan42** [comment]
Thank you for your effort, great!
I will need these edits done:
- use the search bar you did in the homePage 2, much better
- The Price shouldn't have a border like this, and should be bigger & bolder

![image](https://user-images.githubusercontent.com/6496157/113404013-cb9fc880-93a7-11eb-90af-6fb302ed2925.png)

**Comment by MuhammadSamy1** [comment]
here’s last edit for StoreFront page: 

1. edited the search bar.
2. the head BG color.
3. the price.
4. added Footer.

[StoreFront#3.zip](https://github.com/egypt-shops/xshop-web/files/6274962/StoreFront.3.zip)

**Comment by mmostafa74** [comment]
@HMMK99 will implement this page
