### ISSUE TITLE
design the cart view 

### ISSUE THREAD

**Issue by IslamMGM** [egypt-shops/xshop-web#142]
![image](https://user-images.githubusercontent.com/51543417/113040079-ab4def00-9198-11eb-903a-d3dd5f5f0a82.png)

**Comment by AmmarlOsama** [comment]
![01](https://user-images.githubusercontent.com/38835546/113163664-a9d80180-9240-11eb-84d6-edef299b9439.PNG)
![02](https://user-images.githubusercontent.com/38835546/113163672-aa709800-9240-11eb-9b2e-8d32bbe06bb2.PNG)
![03](https://user-images.githubusercontent.com/38835546/113163675-ab092e80-9240-11eb-8f61-6dcbf014a9d4.PNG)

**Comment by IslamMGM** [comment]
Nice work, but you forgot to add the [ update ] button like shown in the wireframe, the colors, and logo as we discussed together

**Comment by AmmarlOsama** [comment]
![1](https://user-images.githubusercontent.com/38835546/113909560-1a01fc80-97d8-11eb-8f5b-147e99cee74c.jpg)
![2](https://user-images.githubusercontent.com/38835546/113909567-1b332980-97d8-11eb-934c-70a579fcd38e.jpg)
![3](https://user-images.githubusercontent.com/38835546/113909570-1bcbc000-97d8-11eb-8446-d7c2e2b44a0b.jpg)

**Comment by AmmarlOsama** [comment]
![Uploading 1.PNG…]()

**Comment by AmmarlOsama** [comment]
![1](https://user-images.githubusercontent.com/38835546/113923799-45d9ae00-97e9-11eb-8797-2e01a04705b9.PNG)
![2](https://user-images.githubusercontent.com/38835546/113923801-46724480-97e9-11eb-8e58-3a6ae875df26.PNG)
[Shopping Cart.zip](https://github.com/egypt-shops/xshop-web/files/6274040/Shopping.Cart.zip)

**Comment by shahwan42** [comment]
Don't close this issue until it's implemented...
When the Backend team implements it, they'll close it.

**Comment by mmostafa74** [comment]
could you enhance this design? @AmmarlOsama

**Comment by shahwan42** [comment]
@mmostafa74 Please have a meeting with him and let him know what you desire to change and outline it here so that he can work on it. be specific, please.

**Comment by AmmarlOsama** [comment]
[
![1](https://user-images.githubusercontent.com/38835546/124305915-04e20300-db66-11eb-99e5-d19ce6944b1c.PNG)
![2](https://user-images.githubusercontent.com/38835546/124305917-057a9980-db66-11eb-9107-e372a5003eaa.PNG)
[Cart last edit.zip](https://github.com/egypt-shops/xshop-web/files/6755921/Cart.last.edit.zip)
](url)

**Comment by AmmarlOsama** [comment]
@mmostafa74

**Comment by AmmarlOsama** [comment]
[cart design.zip](https://github.com/egypt-shops/xshop-web/files/6764027/cart.design.zip)
![cart1](https://user-images.githubusercontent.com/38835546/124468764-d3517d80-dd99-11eb-8f76-27d6975ac519.PNG)
![cart2](https://user-images.githubusercontent.com/38835546/124468771-d482aa80-dd99-11eb-9fe5-81981e913d11.PNG)
![cart3](https://user-images.githubusercontent.com/38835546/124468774-d482aa80-dd99-11eb-9dae-4f5e15da9e91.PNG)

**Comment by AmmarlOsama** [comment]
@mmostafa74 @HMMK99
