### ISSUE TITLE
xshop initial landing page

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#25]
specs:
https://github.com/egypt-shops/xshop-docs/blob/develop/detailed_design/web_pages/home.md

**Comment by AmmarlOsama** [comment]
made the landing page as a home 
![Screenshot from 2020-10-11 16-48-50](https://user-images.githubusercontent.com/38835546/95681783-00457b00-0be2-11eb-89bf-9f1aa3905200.png)
