### ISSUE TITLE
Prepare CustomModelAdmin to inherit from

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#32]
After #31 

- [ ] prepare the custom model admin with different methods to help customize the dashboard for each admin
- [ ] Write tests for each ModelAdmin
    - [ ] CashierAdmin
    - [ ] CustomerAdmin
.... leave the rest for other tasks

**Comment by HMMK99** [comment]
for every model in users other than 'User'
do they just to show the users in each category? if so then we add a new user just by using 'User' model, right?

**Comment by shahwan42** [comment]
The user is already shown, don't do anything about it, show the rest of the models...

**Comment by shahwan42** [comment]
And this issue #32 is for me, don't worry about it
