### ISSUE TITLE
A command to create Fake data

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#47]
command name: fake_data
should be used like this: `python manage.py fake_data`

And create multiple shops with related data (Managers, Sub Managers, Customer, Products, Invoices, Orders, etc.....)
Orders and Invoices should be with different timestamps to generate sensible charts later on

This is very useful for local testing and presentation...

HELP:
https://adamj.eu/tech/2020/09/07/how-to-unit-test-a-django-management-command/
https://docs.djangoproject.com/en/3.1/howto/custom-management-commands/
https://docs.djangoproject.com/en/3.1/topics/testing/tools/#management-commands

**Comment by shahwan42** [comment]
Could you please work on this as part of your AI implementation @ziadnabil ?

**Comment by ziadnabil** [comment]
> Could you please work on this as part of your AI implementation @ziadnabil ?

okay

**Comment by shahwan42** [comment]
let's consider it done :3 xD
