### ISSUE TITLE
Update Invoice Endpoints

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-web#78]
- [x] list invoice per shop
   - [x] manager & authenticated || superuser
- [x] list invoices per customer
  - [x] customer must be the owner of the listed invoices & authenticated
- [x] detail invoice
  - [x] shop
     - [x] shop manager & authenticated
  - [x] customer
     - [x] owner & authenticated

**Comment by mmostafa74** [comment]
implemented in admin panal
